# Generated by Django 6.0.7 on 2026-08-03 07:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('category', models.CharField(choices=[('taxation', 'Taxation'), ('gst', 'GST'), ('compliance', 'Corporate Compliance'), ('accounting', 'Accounting & Bookkeeping'), ('audit', 'Internal Audit & Risk'), ('payroll', 'Payroll & Statutory'), ('general', 'General / Firm News')], default='general', max_length=20)),
                ('excerpt', models.CharField(blank=True, help_text='Short summary shown on the homepage and post list. Auto-filled from content if left blank.', max_length=300)),
                ('content', models.TextField(help_text='Main body of the post. Plain paragraphs, one per line, are fine.')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='posts/%Y/%m/')),
                ('author', models.CharField(default='VGV Konsultancy', max_length=120)),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
